apiVersion: apps/v1
kind: Deployment
metadata:
  name: adi-deploy
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: adi-demo
        image: 482088842115.dkr.ecr.ap-south-1.amazonaws.com/node_dockers
        ports:
        - containerPort: 8001