apiVersion: v1
kind: Pod
metadata:
  name: dys-container
  labels:
    app: dys-container
spec:
  containers:
    - name: dys-container
      image: 482088842115.dkr.ecr.ap-south-1.amazonaws.com/container_registry:latest
      ports:
        - containerPort: 80